### ISSUE TITLE
Could not find preset 2015

### ISSUE THREAD

**Issue by dextermb** [khanglu/react-crossfade-image#5]
Hey there,

I'm attempting to use your package but I seem to be having issues, here's the error:
```
/node_modules/react-crossfade-image/index.es5.js: Couldn't find preset "es2015"
```

Any ideas?

Versions
- React Native: `0.54.0`
- React: `^16.3.1`

**Comment by dextermb** [comment]
I have attempted to add [babel-preset-es2015](https://babeljs.io/docs/en/babel-preset-es2015.html) and/or [babel-preset-react](https://babeljs.io/docs/en/babel-preset-react.html) to my `.babelrc` file but neither of these worked.

**Comment by khanglu** [comment]
Could you post the full error log? It doesn't seem like a problem with the package. Could you try using `babel-preset-env` ?

**Comment by dextermb** [comment]
I've removed the package for now, I'll test with other babel presets when I get a free second and report back here 👍
